ARG BASE_IMAGE=ubuntu:24.04
FROM ${BASE_IMAGE}

### from scratch
#SHELL ["/bin/bash", "-c"]
#ENV DEBIAN_FRONTEND=noninteractive

ENV PATH=/opt/conda/bin:$PATH

WORKDIR /miniconda_install

### from scratch
#RUN echo 'Etc/UTC' > /etc/timezone && \
#    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
#    apt-get update -q -qq && \
#    apt-get install -q -y --no-install-recommends tzdata && \
#    apt install -q -qq -y python3 python3-pip python3-dev wget curl git cmake gnupg software-properties-common build-essential && \
#    apt clean && \    
#    rm -rf /var/lib/apt/lists/*

RUN apt-get update -q -qq && \
    apt-get install -q -y --no-install-recommends tzdata && \
    apt install -q -qq -y python3 python3-pip python3-dev wget curl git cmake gnupg software-properties-common build-essential lsb-release && \
    apt clean && \    
    rm -rf /var/lib/apt/lists/*
    
# install miniconda3
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda && \
    rm Miniconda3-latest-Linux-x86_64.sh

# initialize conda
RUN /opt/conda/bin/conda init bash && \
    echo "source /opt/conda/etc/profile.d/conda.sh" >> /root/.bashrc

# docker build . -f Dockerfile.miniconda --build-arg xeus_python5:24.04
# docker run --net=host -w /userdir -v $(pwd):/userdir -it bash
